server:
  port: 80

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      default-filters:
        - TokenRelay=

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone:
        - http://localhost:8761/eureka/


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: TRACE
  file:
    name: ./log/gateway-service