server:
  port: 80

spring:
  application:
    name: gateway-service


  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone:
        - http://localhost:8761/eureka/


logging:
  level:
    web: debug
  file:
    name: ./log/gateway-service